version: "3"
services:

  staff-service:
    build: staff-service
    ports:
      - "8001:8001"
    environment:
      DB_URL: redis-service


  task-service:
    build: task-service
    ports:
      - "8003:8003"
    environment:
      DB_URL: redis-service


  user-service:
    build: user-service
    ports:
    - "8002:8002"
    environment:
      DB_URL: redis-service


  redis-service:
    image: redis:6.2.5
    ports:
    - "6379:6379"